# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
