# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtweet', '0003_auto_20170112_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
