# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-13 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtweet', '0007_auto_20170113_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timeposted',
            new_name='comment_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timeposted',
            new_name='post_time',
        ),
    ]
